/*
 * MINT_CONFIG.h
 *
 * Created: 02/03/2023 12:04:10 AM
 *  Author: Misra
 */ 


#ifndef MINT_CONFIG_H_
#define MINT_CONFIG_H_


/* MINT_INT_ENABLE, MINT_INT_DISABLE*/
#define MINT_EXINT0_ENABLE  MINT_INT_ENABLE
#define MINT_EXINT1_ENABLE  MINT_INT_DISABLE
#define MINT_EXINT2_ENABLE  MINT_INT_DISABLE

/* MINT_ISC_RISING, MINT_ISC_FALLING, MINT_ISC_ANYLOGIC, MINT_ISC_ANYLEVEL*/
#define MINT_EXINT0_ISC  MINT_ISC_FALLING
#define MINT_EXINT1_ISC  MINT_ISC_FALLING

/* MINT_ISC_RISING, MINT_ISC_FALLING */
#define MINT_EXINT2_ISC  MINT_ISC_FALLING




#endif /* MINT_CONFIG_H_ */